# Generated by Django 3.0.6 on 2020-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('installed_home_id', models.IntegerField()),
                ('manufacturer_id', models.CharField(max_length=20)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('model_number', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=25)),
                ('life_expectancy', models.IntegerField()),
                ('life_used', models.IntegerField()),
                ('alertable', models.BooleanField()),
                ('trend_applicable', models.BooleanField()),
                ('power_rating', models.IntegerField()),
                ('value_stream_id', models.IntegerField()),
                ('location', models.CharField(max_length=45)),

            ],
        ),
    ]
