# Generated by Django 3.0.6 on 2020-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='things',
            name='manufacturer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='things',
            name='model_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='things',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
