# Generated by Django 3.0.6 on 2020-06-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200530_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribersList',
        ),
    ]
