# Generated by Django 3.0.6 on 2020-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200523_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='things',
            name='name',
        ),
        migrations.AddField(
            model_name='things',
            name='description',
            field=models.CharField(default='my coffee machine', max_length=150),
        ),
        migrations.AddField(
            model_name='things',
            name='device_type',
            field=models.CharField(default='coffee machine', max_length=40),
        ),
        migrations.AddField(
            model_name='things',
            name='image_path',
            field=models.CharField(default='coffee machine image path', max_length=100),
        ),
    ]
