# Generated by Django 3.0.6 on 2020-06-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200531_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Neil Armstrong', max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
