# Generated by Django 3.0.6 on 2020-06-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0004_thing_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my coffee machine', max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
