# Generated by Django 3.0.6 on 2020-05-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_things_field27'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='things',
            name='field27',
        ),
    ]
