# Generated by Django 3.0.6 on 2020-06-04 04:49

import dashboard.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='38 Windsor Street', max_length=80)),
                ('zip', models.CharField(default='06001', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic device', max_length=50)),
                ('max_life', models.PositiveIntegerField()),
                ('warranty_days', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='device_catalogue')),
                ('energy_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('safety_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('current_consumption', models.IntegerField()),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(default=dashboard.models.Address(), on_delete=django.db.models.deletion.CASCADE, to='dashboard.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my coffee machine', max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ValueStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='value stream description', max_length=50)),
                ('property_name', models.CharField(default='default property name', max_length=25)),
                ('value', models.FloatField(default=0.0)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='my smart coffee machine', max_length=120)),
                ('purchase_date', models.DateField()),
                ('life_used', models.IntegerField()),
                ('device_model_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.DeviceModels')),
                ('installed_home_id', models.ManyToManyField(to='dashboard.Home')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('value_stream_id', models.ManyToManyField(to='dashboard.ValueStream')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic manufacturer', max_length=150)),
                ('phone_number', models.CharField(default='0000', max_length=14)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Address')),
                ('type_of_device_handled', models.ManyToManyField(to='dashboard.DeviceModels')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_email', models.EmailField(max_length=254)),
                ('date_of_service', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(default='Service completed')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.ServiceProvider')),
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Thing')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic seller', max_length=150)),
                ('phone_number', models.CharField(default='007', max_length=14)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Address')),
                ('type_of_device_sold', models.ManyToManyField(to='dashboard.DeviceModels')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic manufacturer', max_length=50)),
                ('is_certified', models.BooleanField(default=True)),
                ('phone_number', models.CharField(default='007', max_length=14)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Address')),
            ],
        ),
        migrations.AddField(
            model_name='devicemodels',
            name='mfg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Manufacturer'),
        ),
    ]
