# Generated by Django 3.0.6 on 2020-06-02 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetails',
            old_name='owner_email',
            new_name='receipt_email',
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='date_of_service',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='remarks',
            field=models.TextField(default='Service completed'),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.ServiceProvider'),
        ),
        migrations.AlterField(
            model_name='valuestream',
            name='property_name',
            field=models.CharField(default='default property name', max_length=25),
        ),
    ]
