# Generated by Django 3.0.6 on 2020-05-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='device_catalogue'),
        ),
    ]
