# Generated by Django 3.0.6 on 2020-05-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='is_certified',
            field=models.BooleanField(default=True),
        ),
    ]
