# Generated by Django 3.0.6 on 2020-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200530_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='image',
            field=models.ImageField(default='device_catalogue/default.jpg', upload_to='device_catalogue'),
        ),
    ]
