# Generated by Django 3.0.6 on 2020-06-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200603_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.CharField(default='my smart coffee machine', max_length=120),
        ),
    ]
