# Generated by Django 3.0.6 on 2020-06-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200605_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='38 Windsor Street', max_length=82),
        ),
    ]
