# Generated by Django 3.0.6 on 2020-05-23 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20200523_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='38 Whitney Street', max_length=150)),
                ('zip', models.CharField(default='06001', max_length=10)),
                ('country_code', models.CharField(default='64', max_length=10)),
                ('location', models.CharField(default='(-36.9040558,174.7046399)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='value_stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='value stream description', max_length=150)),
                ('property_name', models.CharField(default='property name', max_length=150)),
                ('value', models.FloatField(default=0.0)),
                ('ts', models.DateTimeField()),
                ('quality', models.CharField(default='GOOD', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='things',
            name='owner',
            field=models.ForeignKey(default='asd', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic manufacturer', max_length=150)),
                ('leadtime', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.address')),
            ],
        ),
    ]
