# Generated by Django 3.0.6 on 2020-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200524_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='3]]8 Whitney Street', max_length=150),
        ),
    ]
