# Generated by Django 3.0.6 on 2020-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200525_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='field27',
            field=models.IntegerField(default=15),
        ),
    ]
