# Generated by Django 3.0.6 on 2020-06-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200603_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(default='007', max_length=14),
        ),
    ]
