# Generated by Django 3.0.6 on 2020-05-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200528_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='leadtime',
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='38 Whitney Street', max_length=150),
        ),
        migrations.CreateModel(
            name='DeviceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic device', max_length=50)),
                ('leadtime', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.address')),
            ],
        ),
    ]
