# Generated by Django 3.0.6 on 2020-06-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200603_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='38 Windsor Street', max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(default='06001', max_length=32),
        ),
    ]
