# Generated by Django 3.0.6 on 2020-06-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200603_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='thing',
        ),
    ]
